export const GET_STATUS_REQUEST = 'status.GET_STATUS_REQUEST'
export const GET_STATUS_SUCCESS = 'status.GET_STATUS_SUCCESS'
export const GET_STATUS_FAILED = 'status.GET_STATUS_FAILED'

export const GET_STATISTIC_REQUEST = 'status.GET_STATISTIC_REQUEST'
export const GET_STATISTIC_SUCCESS = 'status.GET_STATISTIC_SUCCESS'
export const GET_STATISTIC_FAILED = 'status.GET_STATISTIC_FAILED'
